fos_user_profile_show:
    pattern: /privee/profil
    defaults: { _controller: FOSUserBundle:Profile:show }
    
fos_user_profile_edit:
    pattern: /privee/gestion-profil
    defaults: { _controller: FOSUserBundle:Profile:edit}
    
    


