language: php
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
php:
  - 5.6
  - 7.0
  - hhvm # on Trusty only
  - nightly
env: # important!
matrix:
  include:
  - php: 7.0
    env: KEY=VALUE
  allow_failures:
  - php: 7.0
    env: KEY=VALUE

# branche Ok
branches:
    only:    
    - develop

