version: '2'

services:
    web:
        build: .
        ports:
            - "8001:8001"
        volumes:
            - ./:/usr/src/myapp
            - "./timezone.ini:/usr/local/etc/php/conf.d/timezone.ini"
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - db:db
    db:
        image: mysql:latest
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3308:3308"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin:latest
        ports:
            - "8082:80"
        links:
            - db:db
