Admin_accueil:
    pattern: /admin
    defaults: { _controller: AdminBundle:Admin:index }
    
Admin_liste_client:
    pattern: /admin/clients/
    defaults: { _controller: AdminBundle:Admin:clients }
    
Admin_liste_client_detail:
    pattern: /admin/clients/listeClient
    defaults: { _controller: AdminBundle:Admin:adminListeClient}     
    
Admin_infos_client:
    pattern: /admin/clients/infos-client
    defaults: { _controller: AdminBundle:Admin:infosClient } 

Admin_ajout__argent_client:
    pattern: /admin/clients/ajouter-argent
    defaults: { _controller: AdminBundle:Admin:ajouterArgent }

Admin_code:
    pattern: /admin/code-de-la-route
    defaults: { _controller: AdminBundle:Admin:code }

Admin_permis:
    pattern: /admin/permis-B
    defaults: { _controller: AdminBundle:Admin:permis }

Admin_tarifs:
    pattern: /admin/tarifs
    defaults: { _controller: AdminBundle:Admin:tarifs }

Admin_retrouver:
    pattern: /admin/nous-trouver
    defaults: { _controller: AdminBundle:Admin:retrouver }
    

