Moniteur_accueil:
    path:     /
    defaults: { _controller: MoniteurBundle:Moniteur:index }
    
Moniteur_calendrier:
    path:     /calendrier
    defaults: { _controller: CalendrierBundle:Calendrier:calendrierMoniteur }
    
Moniteur_calendrierPagination:
    path: /calendrier/pagination
    defaults: {_controller: CalendrierBundle:Calendrier:paginationMoniteur }     
    
    
fos_moniteur_profile_show:
    pattern: /profil
    defaults: { _controller: FOSUserBundle:Profile:showMoniteur }
    
fos_moniteur_profile_edit:
    pattern: /gestion-profil
    defaults: { _controller: FOSUserBundle:Profile:editMoniteur}    

