Privee_accueil:
    pattern: /privee/
    defaults: { _controller: PriveeBundle:Privee:index}
    
Privee_mail:
    pattern: /privee/mail
    defaults: { _controller: PriveeBundle:Privee:mail}
    
Privee_code:
    pattern: /privee/code-de-la-route
    defaults: { _controller: PriveeBundle:Privee:code }

Privee_permis:
    pattern: /privee/permis-B
    defaults: { _controller: PriveeBundle:Privee:permis }

Privee_tarifs:
    pattern: /privee/tarifs
    defaults: { _controller: PriveeBundle:Privee:tarifs }

Privee_nouveaux:
    pattern: /privee/nouveaux
    defaults: { _controller: PriveeBundle:Privee:nouveaux}

Privee_retrouver:
    pattern: /privee/nous-trouver
    defaults: { _controller: PriveeBundle:Privee:retrouver }