Privee_accueil:
    path: /
    defaults: { _controller: PriveeBundle:Privee:index }
    
Privee_calendrier:
    path: /calendrier
    defaults: {_controller: CalendrierBundle:Calendrier:calendrier }

Privee_calendrierPagination:
    path: /calendrier/Pagination
    defaults: {_controller: CalendrierBundle:Calendrier:pagination }