Privee_accueil:
    path: /
    defaults: { _controller: PriveeBundle:Privee:index }
    
Privee_calendrier:
    path: /calendrier
    defaults: {_controller: CalendrierBundle:Calendrier:calendrier }
    
Privee_calendrier:
    path: /calendrierContenu
    defaults: {_controller: CalendrierBundle:Calendrier:calendrierContenu }    
    
Privee_reserver:
    path: /calendrier/reserver
    defaults: { _controller: ReservationBundle:Reservation:reserver }    

Privee_calendrierPagination:
    path: /calendrier/Pagination
    defaults: {_controller: CalendrierBundle:Calendrier:pagination }